name: ur5e_vlm_environment
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core Scientific Computing
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  
  # Computer Vision
  - opencv
  - pillow
  - imageio
  
  # Deep Learning & AI
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # GPU support
  - transformers
  - tokenizers
  - datasets
  - accelerate
  - safetensors
  - sentence-transformers
  
  # Audio Processing
  - librosa
  - pyaudio
  - ffmpeg
  - portaudio
  
  # Computer Vision & 3D
  - vtk
  - trimesh
  - open3d
  
  # Hardware Interface
  - pyserial
  
  # Development Tools
  - jupyter
  - ipython
  - black
  - flake8
  - pytest
  - setuptools
  - wheel
  - pip
  
  # System Dependencies
  - cmake
  - pkg-config
  - gcc_linux-64
  - gxx_linux-64
  
  # Additional dependencies via pip
  - pip:
    # RealSense Camera
    - pyrealsense2
    
    # Audio Processing
    - sounddevice
    
    # Natural Language Processing
    - spacy
    - openai-whisper
    - pyttsx3
    
    # ROS2 Dependencies (install via pip for conda compatibility)
    - rclpy
    - geometry-msgs
    - sensor-msgs
    - std-msgs
    - trajectory-msgs
    - tf2-ros
    - cv-bridge
    - moveit-msgs
    - control-msgs
    - visualization-msgs
    
    # Robotics & Kinematics
    - robotics-toolbox-python
    - spatialmath-python
    - modern-robotics
    - ikpy
    
    # Gazebo/Simulation (if available via pip)
    - pybullet  # Alternative physics simulation
    
    # Construction & Domain-Specific
    - rasa  # NLP framework for construction domain
    - yaml
    
    # Additional ML/AI tools
    - huggingface-hub
    - evaluate
    - gradio  # For creating interfaces
    
    # Visualization
    - plotly
    - seaborn
    
    # Utilities
    - tqdm
    - click
    - pydantic
    - requests
    - aiohttp
    
    # Testing & Development
    - pytest-asyncio
    - pytest-mock
    
    # Audio System Libraries (Linux specific)
    - pyalsaaudio  # ALSA audio interface
    - python-pulse-control  # PulseAudio control